---
deprecations:
  - |
    ML2/OVN plugin does not support versions below 20.06. The Neutron plugin
    expects to read the "Chassis" register configuration in "other_config"
    field only.
other:
  - |
    Since OVN 20.06, the "Chassis" register configuration is stored in the
    "other_config" field and replicated into "external_ids". This replication
    is stopped in OVN 22.09. The ML2/OVN plugin retrieves the "Chassi"
    configuration from the "other_config" field only. That makes Neutron
    not compatible with OVN versions below 20.06.
